import type { LucideIcon } from "lucide-react";
import { Sun, Snowflake, Gem, Sprout, Crown, Shirt } from "lucide-react";

export type Fabric = {
  id: string;
  name: string;
  brand: string;
  price: number;
  season: "صيفي" | "شتوي" | "دائم";
  material: string;
  feel: string;
  color: string;
  colorHex: string;
  rating: number;
  reviewCount: number;
  available: boolean;
  tailorId: string;
  tags: string[];
  description: string;
};

export type Tailor = {
  id: string;
  name: string;
  city: string;
  district: string;
  rating: number;
  reviewCount: number;
  logoHue: number;
  coverHue: number;
  hours: string;
  about: string;
  phone: string;
  whatsapp: string;
  location: {
    lat: number;
    lng: number;
    address: string;
  };
  fabricCount: number;
};

export type Measurement = {
  id: string;
  tailorId: string;
  tailorName: string;
  date: string;
  values: { label: string; value: number; unit: string }[];
  notes?: string;
};

export type FabricHistory = {
  id: string;
  fabricId: string;
  tailorId: string;
  date: string;
  rating: number;
  notes?: string;
};

export const tailors: Tailor[] = [
  {
    id: "t1",
    name: "خياط الفخامة",
    city: "الرياض",
    district: "حي التخصصي",
    rating: 4.9,
    reviewCount: 312,
    logoHue: 165,
    coverHue: 165,
    hours: "٩ ص - ١١ م",
    about: "خياط رجالي فاخر متخصص في الثياب السعودية التقليدية منذ ١٩٩٨.",
    phone: "0555000111",
    whatsapp: "0555000111",
    location: {
      lat: 24.753,
      lng: 46.673,
      address: "طريق الأمير محمد بن سلمان، حي التخصصي، الرياض",
    },
    fabricCount: 128,
  },
  {
    id: "t2",
    name: "خياط المتروك",
    city: "الرياض",
    district: "حي العليا",
    rating: 4.8,
    reviewCount: 210,
    logoHue: 82,
    coverHue: 40,
    hours: "١٠ ص - ١٢ ص",
    about: "خبرة في الأقمشة اليابانية والإنجليزية الفاخرة.",
    phone: "0555000222",
    whatsapp: "0555000222",
    location: {
      lat: 24.6905,
      lng: 46.6855,
      address: "شارع العليا، حي العليا، الرياض",
    },
    fabricCount: 96,
  },
  {
    id: "t3",
    name: "بيت الخياطة الأنيق",
    city: "جدة",
    district: "حي الروضة",
    rating: 4.7,
    reviewCount: 178,
    logoHue: 200,
    coverHue: 210,
    hours: "١١ ص - ١ ص",
    about: "تفصيل عصري مع لمسات كلاسيكية.",
    phone: "0555000333",
    whatsapp: "0555000333",
    location: {
      lat: 21.5805,
      lng: 39.1805,
      address: "شارع صاري، حي الروضة، جدة",
    },
    fabricCount: 74,
  },
  {
    id: "t4",
    name: "خياط الديوان",
    city: "الدمام",
    district: "حي الشاطئ",
    rating: 4.9,
    reviewCount: 402,
    logoHue: 25,
    coverHue: 30,
    hours: "٨ ص - ١٠ م",
    about: "أقدم بيوت التفصيل في المنطقة الشرقية.",
    phone: "0555000444",
    whatsapp: "0555000444",
    location: {
      lat: 26.426,
      lng: 50.102,
      address: "شارع الكورنيش، حي الشاطئ، الدمام",
    },
    fabricCount: 152,
  },
  {
    id: "t5",
    name: "خياط الأصالة",
    city: "الرياض",
    district: "حي النرجس",
    rating: 4.6,
    reviewCount: 145,
    logoHue: 340,
    coverHue: 340,
    hours: "٩ ص - ١٢ ص",
    about: "تفصيل يجمع بين الأصالة والذوق العصري بأسعار مناسبة.",
    phone: "0555000555",
    whatsapp: "0555000555",
    location: {
      lat: 24.846,
      lng: 46.7,
      address: "شارع النرجس، حي النرجس، الرياض",
    },
    fabricCount: 88,
  },
  {
    id: "t6",
    name: "بيت النخبة للتفصيل",
    city: "مكة المكرمة",
    district: "حي العزيزية",
    rating: 4.8,
    reviewCount: 267,
    logoHue: 260,
    coverHue: 270,
    hours: "١٠ ص - ٢ ص",
    about: "متخصصون في أثواب الحرمين والمناسبات الدينية.",
    phone: "0555000666",
    whatsapp: "0555000666",
    location: {
      lat: 21.4105,
      lng: 39.8155,
      address: "شارع العزيزية، حي العزيزية، مكة المكرمة",
    },
    fabricCount: 112,
  },
  {
    id: "t7",
    name: "خياط الملوك",
    city: "الطائف",
    district: "حي شهار",
    rating: 4.9,
    reviewCount: 189,
    logoHue: 130,
    coverHue: 140,
    hours: "٨ ص - ١١ م",
    about: "خبرة ٤٠ سنة في تفصيل الثوب السعودي الكلاسيكي.",
    phone: "0555000777",
    whatsapp: "0555000777",
    location: {
      lat: 21.2875,
      lng: 40.4605,
      address: "شارع شهار، حي شهار، الطائف",
    },
    fabricCount: 205,
  },
  {
    id: "t8",
    name: "خياط الأمير",
    city: "أبها",
    district: "حي المنسك",
    rating: 4.7,
    reviewCount: 98,
    logoHue: 15,
    coverHue: 20,
    hours: "٩ ص - ١٠ م",
    about: "أول بيت تفصيل رجالي متخصص في الجنوب.",
    phone: "0555000888",
    whatsapp: "0555000888",
    location: {
      lat: 18.2245,
      lng: 42.5085,
      address: "شارع المنسك، حي المنسك، أبها",
    },
    fabricCount: 67,
  },
  {
    id: "t9",
    name: "دار الحياكة الملكية",
    city: "الرياض",
    district: "حي الملقا",
    rating: 5.0,
    reviewCount: 512,
    logoHue: 210,
    coverHue: 220,
    hours: "١٠ ص - ١ ص",
    about: "أقمشة يابانية وإيطالية حصرية · خدمة VIP.",
    phone: "0555000999",
    whatsapp: "0555000999",
    location: {
      lat: 24.775,
      lng: 46.624,
      address: "شارع الملقا، حي الملقا، الرياض",
    },
    fabricCount: 340,
  },
  {
    id: "t10",
    name: "خياط الواحة",
    city: "بريدة",
    district: "حي الصفراء",
    rating: 4.5,
    reviewCount: 76,
    logoHue: 50,
    coverHue: 55,
    hours: "٧ ص - ١٠ م",
    about: "تفصيل شعبي بجودة عالية وأسعار في متناول الجميع.",
    phone: "0555000101",
    whatsapp: "0555000101",
    location: {
      lat: 26.3385,
      lng: 43.9595,
      address: "شارع الصفراء، حي الصفراء، بريدة",
    },
    fabricCount: 54,
  },
];

export const fabrics: Fabric[] = [
  {
    id: "f1",
    name: "تويوبو سميراميس بلس",
    brand: "Toyobo",
    price: 350,
    season: "صيفي",
    material: "قطن ياباني ١٠٠٪",
    feel: "ناعم ومتماسك",
    color: "أبيض ناصع",
    colorHex: "#f8f5ee",
    rating: 4.9,
    reviewCount: 218,
    available: true,
    tailorId: "t1",
    tags: ["رسمي", "دوام", "مناسبات"],
    description:
      "قماش تويوبو الياباني الشهير بجودته العالية، لا يكش، مقاوم للترييش، مناسب للدوام والمناسبات الرسمية طوال العام.",
  },
  {
    id: "f2",
    name: "شكيبو كريمي فاخر",
    brand: "Shikibo",
    price: 420,
    season: "صيفي",
    material: "قطن ياباني مع بوليستر",
    feel: "بارد وخفيف",
    color: "كريمي دافئ",
    colorHex: "#f0e8d6",
    rating: 4.8,
    reviewCount: 156,
    available: true,
    tailorId: "t2",
    tags: ["يومي", "صيف", "خفيف"],
    description: "قماش شكيبو بلمسة كريمية دافئة، مثالي لأجواء الصيف.",
  },
  {
    id: "f3",
    name: "سلك إنجليزي أبيض",
    brand: "English Silk",
    price: 680,
    season: "دائم",
    material: "حرير إنجليزي فاخر",
    feel: "ملكي وانسيابي",
    color: "أبيض لؤلؤي",
    colorHex: "#faf6ec",
    rating: 5.0,
    reviewCount: 89,
    available: true,
    tailorId: "t1",
    tags: ["مناسبات", "فاخر", "أعراس"],
    description: "قماش حرير إنجليزي للمناسبات الفاخرة والأعراس.",
  },
  {
    id: "f4",
    name: "صوف بريطاني رمادي",
    brand: "Windsor Wool",
    price: 520,
    season: "شتوي",
    material: "صوف بريطاني ١٠٠٪",
    feel: "دافئ وثقيل",
    color: "رمادي فحمي",
    colorHex: "#4a4a52",
    rating: 4.7,
    reviewCount: 142,
    available: true,
    tailorId: "t3",
    tags: ["شتاء", "رسمي", "دوام"],
    description: "صوف بريطاني فاخر للأجواء الباردة.",
  },
  {
    id: "f5",
    name: "قطن مصري ناعم",
    brand: "Nile Cotton",
    price: 240,
    season: "صيفي",
    material: "قطن مصري طويل التيلة",
    feel: "ناعم كالحرير",
    color: "أوف وايت",
    colorHex: "#f3ecdd",
    rating: 4.6,
    reviewCount: 305,
    available: true,
    tailorId: "t4",
    tags: ["يومي", "اقتصادي"],
    description: "قطن مصري بجودة عالية وسعر مناسب.",
  },
  {
    id: "f6",
    name: "كتان إيطالي بيج",
    brand: "Milano Linen",
    price: 460,
    season: "صيفي",
    material: "كتان إيطالي",
    feel: "بارد وطبيعي",
    color: "بيج فاتح",
    colorHex: "#e8dcc4",
    rating: 4.5,
    reviewCount: 74,
    available: false,
    tailorId: "t3",
    tags: ["كاجوال", "طبيعي", "صيف"],
    description: "كتان إيطالي طبيعي بلون بيج راقٍ.",
  },
  {
    id: "f7",
    name: "تويوبو بلاتينيوم",
    brand: "Toyobo",
    price: 480,
    season: "دائم",
    material: "قطن ياباني ممزوج",
    feel: "متوسط ومتماسك",
    color: "أبيض بلمسة فضية",
    colorHex: "#f2f0e8",
    rating: 4.9,
    reviewCount: 267,
    available: true,
    tailorId: "t2",
    tags: ["رسمي", "فاخر"],
    description: "الفئة البلاتينية من تويوبو، ملمس فاخر ومتانة عالية.",
  },
  {
    id: "f8",
    name: "شتوي كشمير مطعّم",
    brand: "Kashmir Blend",
    price: 720,
    season: "شتوي",
    material: "كشمير مع صوف",
    feel: "دافئ فاخر",
    color: "بيج غامق",
    colorHex: "#a08464",
    rating: 4.8,
    reviewCount: 63,
    available: true,
    tailorId: "t1",
    tags: ["شتاء", "فاخر", "مناسبات"],
    description: "خلطة كشمير وصوف للشتاء الفاخر.",
  },
  {
    id: "f9",
    name: "دورما ياباني كلاسيك",
    brand: "Dormeuil",
    price: 550,
    season: "دائم",
    material: "قطن ياباني ممتاز",
    feel: "ناعم وفاخر",
    color: "أبيض عاجي",
    colorHex: "#f5f0e1",
    rating: 4.9,
    reviewCount: 198,
    available: true,
    tailorId: "t9",
    tags: ["رسمي", "فاخر", "دوام"],
    description: "قماش دورما الفرنسي المصنّع في اليابان، خيار المسؤولين والوجهاء.",
  },
  {
    id: "f10",
    name: "زفير صيفي خفيف",
    brand: "Zephyr",
    price: 280,
    season: "صيفي",
    material: "قطن مع فسكوز",
    feel: "خفيف كالنسيم",
    color: "أبيض مائل للأزرق",
    colorHex: "#eef2f3",
    rating: 4.5,
    reviewCount: 121,
    available: true,
    tailorId: "t5",
    tags: ["صيف", "يومي", "خفيف"],
    description: "قماش زفير للأجواء الحارة، تنفّس ممتاز وخفة عالية.",
  },
  {
    id: "f11",
    name: "أرابيسك ذهبي",
    brand: "Arabesque",
    price: 890,
    season: "دائم",
    material: "حرير مع قطن مطرّز",
    feel: "فخم وثقيل",
    color: "بيج ذهبي",
    colorHex: "#c9a875",
    rating: 4.9,
    reviewCount: 45,
    available: true,
    tailorId: "t6",
    tags: ["مناسبات", "أعراس", "فاخر جدا"],
    description: "قماش أرابيسك بلمسات ذهبية للأعراس والمناسبات الملكية.",
  },
  {
    id: "f12",
    name: "بريستيج شتوي",
    brand: "Prestige",
    price: 610,
    season: "شتوي",
    material: "صوف مع كشمير ٢٠٪",
    feel: "دافئ ومتماسك",
    color: "بني داكن",
    colorHex: "#6b4a2b",
    rating: 4.7,
    reviewCount: 87,
    available: true,
    tailorId: "t7",
    tags: ["شتاء", "رسمي", "فاخر"],
    description: "قماش بريستيج للشتاء، دفء عالي مع أناقة كلاسيكية.",
  },
  {
    id: "f13",
    name: "لوتس صيفي أبيض",
    brand: "Lotus",
    price: 195,
    season: "صيفي",
    material: "قطن بوليستر",
    feel: "خفيف عملي",
    color: "أبيض",
    colorHex: "#fbfbf7",
    rating: 4.3,
    reviewCount: 412,
    available: true,
    tailorId: "t10",
    tags: ["يومي", "اقتصادي", "صيف"],
    description: "قماش لوتس اقتصادي، مناسب للاستخدام اليومي والدوام.",
  },
  {
    id: "f14",
    name: "أورينتال هاش",
    brand: "Oriental",
    price: 380,
    season: "دائم",
    material: "قطن مصري ممزوج",
    feel: "متوسط الوزن",
    color: "رمادي فاتح",
    colorHex: "#c8c6c0",
    rating: 4.6,
    reviewCount: 178,
    available: true,
    tailorId: "t8",
    tags: ["رسمي", "دوام", "مميز"],
    description: "قماش أورينتال بلمسة عصرية ولون رمادي أنيق.",
  },
  {
    id: "f15",
    name: "روزا كاجوال",
    brand: "Rosa",
    price: 320,
    season: "صيفي",
    material: "كتان مع قطن",
    feel: "طبيعي ومريح",
    color: "بيج ترابي",
    colorHex: "#d4c4a8",
    rating: 4.4,
    reviewCount: 95,
    available: false,
    tailorId: "t5",
    tags: ["كاجوال", "صيف", "طبيعي"],
    description: "قماش روزا الكاجوال بلون ترابي دافئ.",
  },
  {
    id: "f16",
    name: "امبريال بلاك تاي",
    brand: "Imperial",
    price: 950,
    season: "دائم",
    material: "حرير إيطالي ممزوج",
    feel: "لامع وفخم",
    color: "أسود بلمسة زرقاء",
    colorHex: "#1a1e2e",
    rating: 5.0,
    reviewCount: 34,
    available: true,
    tailorId: "t9",
    tags: ["مناسبات", "رسمي جدا", "VIP"],
    description: "قماش امبريال الحصري للسهرات الرسمية والمناسبات الخاصة.",
  },
  {
    id: "f17",
    name: "سماوي ياباني",
    brand: "Sky Japan",
    price: 410,
    season: "صيفي",
    material: "قطن ياباني ١٠٠٪",
    feel: "بارد ومريح",
    color: "أبيض بلمسة سماوية",
    colorHex: "#eaf0f5",
    rating: 4.7,
    reviewCount: 143,
    available: true,
    tailorId: "t6",
    tags: ["صيف", "رسمي", "مميز"],
    description: "قماش سماوي ياباني بلمسة زرقاء ناعمة، مثالي للصيف.",
  },
  {
    id: "f18",
    name: "ريتز كريمي",
    brand: "Ritz",
    price: 470,
    season: "دائم",
    material: "قطن ممتاز",
    feel: "ناعم متماسك",
    color: "كريمي فاتح",
    colorHex: "#f4ecdc",
    rating: 4.8,
    reviewCount: 221,
    available: true,
    tailorId: "t7",
    tags: ["رسمي", "دوام", "فاخر"],
    description: "قماش ريتز الكريمي، خيار مثالي للدوام والمناسبات.",
  },
];

export const categories: { id: string; label: string; icon: LucideIcon }[] = [
  { id: "summer", label: "صيفي", icon: Sun },
  { id: "winter", label: "شتوي", icon: Snowflake },
  { id: "luxury", label: "فاخر", icon: Gem },
  { id: "cotton", label: "قطن", icon: Sprout },
  { id: "formal", label: "رسمي", icon: Crown },
  { id: "daily", label: "يومي", icon: Shirt },
];

export const measurements: Measurement[] = [
  {
    id: "m1",
    tailorId: "t1",
    tailorName: "خياط الفخامة",
    date: "٢٢ مايو ٢٠٢٤",
    values: [
      { label: "الطول", value: 154, unit: "سم" },
      { label: "الكتف", value: 48, unit: "سم" },
      { label: "الصدر", value: 108, unit: "سم" },
      { label: "الرقبة", value: 42, unit: "سم" },
      { label: "الكم", value: 62, unit: "سم" },
      { label: "الوسع", value: 128, unit: "سم" },
    ],
    notes: "ثوب رسمي - رقبة كلاسيكية، كبك مغلق.",
  },
  {
    id: "m2",
    tailorId: "t2",
    tailorName: "خياط المتروك",
    date: "١٠ مارس ٢٠٢٤",
    values: [
      { label: "الطول", value: 153, unit: "سم" },
      { label: "الكتف", value: 47, unit: "سم" },
      { label: "الصدر", value: 106, unit: "سم" },
      { label: "الرقبة", value: 42, unit: "سم" },
      { label: "الكم", value: 61, unit: "سم" },
      { label: "الوسع", value: 126, unit: "سم" },
    ],
    notes: "ثوب دوام يومي.",
  },
  {
    id: "m3",
    tailorId: "t1",
    tailorName: "خياط الفخامة",
    date: "٥ نوفمبر ٢٠٢٣",
    values: [
      { label: "الطول", value: 152, unit: "سم" },
      { label: "الكتف", value: 47, unit: "سم" },
      { label: "الصدر", value: 105, unit: "سم" },
      { label: "الرقبة", value: 41, unit: "سم" },
      { label: "الكم", value: 60, unit: "سم" },
      { label: "الوسع", value: 124, unit: "سم" },
    ],
  },
  {
    id: "m4",
    tailorId: "t9",
    tailorName: "دار الحياكة الملكية",
    date: "١٨ يونيو ٢٠٢٤",
    values: [
      { label: "الطول", value: 155, unit: "سم" },
      { label: "الكتف", value: 48, unit: "سم" },
      { label: "الصدر", value: 109, unit: "سم" },
      { label: "الرقبة", value: 42, unit: "سم" },
      { label: "الكم", value: 63, unit: "سم" },
      { label: "الوسع", value: 130, unit: "سم" },
    ],
    notes: "ثوب عرس - رقبة كبك مطرّز بخيوط ذهبية.",
  },
  {
    id: "m5",
    tailorId: "t6",
    tailorName: "بيت النخبة للتفصيل",
    date: "٢ فبراير ٢٠٢٤",
    values: [
      { label: "الطول", value: 153, unit: "سم" },
      { label: "الكتف", value: 47, unit: "سم" },
      { label: "الصدر", value: 107, unit: "سم" },
      { label: "الرقبة", value: 42, unit: "سم" },
      { label: "الكم", value: 62, unit: "سم" },
      { label: "الوسع", value: 127, unit: "سم" },
    ],
    notes: "ثوب عمرة - قماش خفيف.",
  },
  {
    id: "m6",
    tailorId: "t7",
    tailorName: "خياط الملوك",
    date: "٢٥ ديسمبر ٢٠٢٣",
    values: [
      { label: "الطول", value: 153, unit: "سم" },
      { label: "الكتف", value: 47, unit: "سم" },
      { label: "الصدر", value: 106, unit: "سم" },
      { label: "الرقبة", value: 41, unit: "سم" },
      { label: "الكم", value: 61, unit: "سم" },
      { label: "الوسع", value: 125, unit: "سم" },
    ],
  },
];

export const fabricHistory: FabricHistory[] = [
  { id: "h1", fabricId: "f1", tailorId: "t1", date: "مايو ٢٠٢٤", rating: 5, notes: "ممتاز للدوام" },
  { id: "h2", fabricId: "f3", tailorId: "t1", date: "مارس ٢٠٢٤", rating: 5, notes: "لعُرس الأخ" },
  { id: "h3", fabricId: "f5", tailorId: "t4", date: "يناير ٢٠٢٤", rating: 4 },
  {
    id: "h4",
    fabricId: "f9",
    tailorId: "t9",
    date: "يونيو ٢٠٢٤",
    rating: 5,
    notes: "لاجتماع رسمي",
  },
  { id: "h5", fabricId: "f11", tailorId: "t6", date: "أبريل ٢٠٢٤", rating: 5, notes: "عرس الوالد" },
  {
    id: "h6",
    fabricId: "f12",
    tailorId: "t7",
    date: "ديسمبر ٢٠٢٣",
    rating: 4,
    notes: "شتاء الرياض",
  },
  { id: "h7", fabricId: "f17", tailorId: "t6", date: "أغسطس ٢٠٢٣", rating: 5 },
];

export const savedFabricIds = ["f1", "f3", "f7", "f8", "f9", "f11", "f16", "f17"];

export function fabricById(id: string) {
  return fabrics.find((f) => f.id === id);
}
export function tailorById(id: string) {
  return tailors.find((t) => t.id === id);
}
export function fabricsByTailor(id: string) {
  return fabrics.filter((f) => f.tailorId === id);
}
