/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MeasurementsRouteImport } from './routes/measurements'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as TailorIdRouteImport } from './routes/tailor.$id'
import { Route as ShopStaffRouteImport } from './routes/shop.staff'
import { Route as ShopInventoryRouteImport } from './routes/shop.inventory'
import { Route as ShopInboxRouteImport } from './routes/shop.inbox'
import { Route as ShopCustomersRouteImport } from './routes/shop.customers'
import { Route as FabricIdRouteImport } from './routes/fabric.$id'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MeasurementsRoute = MeasurementsRouteImport.update({
  id: '/measurements',
  path: '/measurements',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const TailorIdRoute = TailorIdRouteImport.update({
  id: '/tailor/$id',
  path: '/tailor/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopStaffRoute = ShopStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => ShopRoute,
} as any)
const ShopInventoryRoute = ShopInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => ShopRoute,
} as any)
const ShopInboxRoute = ShopInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCustomersRoute = ShopCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => ShopRoute,
} as any)
const FabricIdRoute = FabricIdRouteImport.update({
  id: '/fabric/$id',
  path: '/fabric/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/measurements': typeof MeasurementsRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/shop': typeof ShopRouteWithChildren
  '/fabric/$id': typeof FabricIdRoute
  '/shop/customers': typeof ShopCustomersRoute
  '/shop/inbox': typeof ShopInboxRoute
  '/shop/inventory': typeof ShopInventoryRoute
  '/shop/staff': typeof ShopStaffRoute
  '/tailor/$id': typeof TailorIdRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/measurements': typeof MeasurementsRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/fabric/$id': typeof FabricIdRoute
  '/shop/customers': typeof ShopCustomersRoute
  '/shop/inbox': typeof ShopInboxRoute
  '/shop/inventory': typeof ShopInventoryRoute
  '/shop/staff': typeof ShopStaffRoute
  '/tailor/$id': typeof TailorIdRoute
  '/shop': typeof ShopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/measurements': typeof MeasurementsRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/shop': typeof ShopRouteWithChildren
  '/fabric/$id': typeof FabricIdRoute
  '/shop/customers': typeof ShopCustomersRoute
  '/shop/inbox': typeof ShopInboxRoute
  '/shop/inventory': typeof ShopInventoryRoute
  '/shop/staff': typeof ShopStaffRoute
  '/tailor/$id': typeof TailorIdRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/measurements'
    | '/profile'
    | '/saved'
    | '/search'
    | '/shop'
    | '/fabric/$id'
    | '/shop/customers'
    | '/shop/inbox'
    | '/shop/inventory'
    | '/shop/staff'
    | '/tailor/$id'
    | '/shop/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/measurements'
    | '/profile'
    | '/saved'
    | '/search'
    | '/fabric/$id'
    | '/shop/customers'
    | '/shop/inbox'
    | '/shop/inventory'
    | '/shop/staff'
    | '/tailor/$id'
    | '/shop'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/measurements'
    | '/profile'
    | '/saved'
    | '/search'
    | '/shop'
    | '/fabric/$id'
    | '/shop/customers'
    | '/shop/inbox'
    | '/shop/inventory'
    | '/shop/staff'
    | '/tailor/$id'
    | '/shop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  MeasurementsRoute: typeof MeasurementsRoute
  ProfileRoute: typeof ProfileRoute
  SavedRoute: typeof SavedRoute
  SearchRoute: typeof SearchRoute
  ShopRoute: typeof ShopRouteWithChildren
  FabricIdRoute: typeof FabricIdRoute
  TailorIdRoute: typeof TailorIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/measurements': {
      id: '/measurements'
      path: '/measurements'
      fullPath: '/measurements'
      preLoaderRoute: typeof MeasurementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/tailor/$id': {
      id: '/tailor/$id'
      path: '/tailor/$id'
      fullPath: '/tailor/$id'
      preLoaderRoute: typeof TailorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/staff': {
      id: '/shop/staff'
      path: '/staff'
      fullPath: '/shop/staff'
      preLoaderRoute: typeof ShopStaffRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/inventory': {
      id: '/shop/inventory'
      path: '/inventory'
      fullPath: '/shop/inventory'
      preLoaderRoute: typeof ShopInventoryRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/inbox': {
      id: '/shop/inbox'
      path: '/inbox'
      fullPath: '/shop/inbox'
      preLoaderRoute: typeof ShopInboxRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/customers': {
      id: '/shop/customers'
      path: '/customers'
      fullPath: '/shop/customers'
      preLoaderRoute: typeof ShopCustomersRouteImport
      parentRoute: typeof ShopRoute
    }
    '/fabric/$id': {
      id: '/fabric/$id'
      path: '/fabric/$id'
      fullPath: '/fabric/$id'
      preLoaderRoute: typeof FabricIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ShopRouteChildren {
  ShopCustomersRoute: typeof ShopCustomersRoute
  ShopInboxRoute: typeof ShopInboxRoute
  ShopInventoryRoute: typeof ShopInventoryRoute
  ShopStaffRoute: typeof ShopStaffRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopCustomersRoute: ShopCustomersRoute,
  ShopInboxRoute: ShopInboxRoute,
  ShopInventoryRoute: ShopInventoryRoute,
  ShopStaffRoute: ShopStaffRoute,
  ShopIndexRoute: ShopIndexRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  MeasurementsRoute: MeasurementsRoute,
  ProfileRoute: ProfileRoute,
  SavedRoute: SavedRoute,
  SearchRoute: SearchRoute,
  ShopRoute: ShopRouteWithChildren,
  FabricIdRoute: FabricIdRoute,
  TailorIdRoute: TailorIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
